# action.yml
name: 'semver-action'
branding:
  icon: 'tag'
  color: 'blue'
description: 'bump semantic version'
inputs:
  SOURCE:
    description: 'The folder containing another repo that you want the semver tag added to.'
    required: True
  DEFAULT_BUMP:
    description: 'major, minor or patch, the default is patch.'
    required: false
  WITH_V: 
    description: 'With "v" prefix.'
    required: false
  DRY_RUN: 
    description: 'Dry run.'
    required: false
  RELEASE_BRANCHES: 
    description: 'Release branches.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "SOURCE: ${{ inputs.SOURCE }}"
    - "DEFAULT_DUMP: ${{ inputs.DEFAULT_BUMP }}"
    - "WITH_V: ${{ inputs.WITH_V }}"
    - "DRY_RUN: ${{ inputs.DRY_RUN }}"
    - "RELEASE_BRANCHES: ${{ inputs.RELEASE_BRANCHES }}"
