on: [push]

jobs:
  semver-action:
    runs-on: ubuntu-latest
    name: semver-action

    steps:
    - uses: actions/checkout@v2
      with:
        repository: stugit/semver-action
        fetch-depth: 0
  

    - uses: stugit/semver-action@master
      with:
        SOURCE: "${GITHUB_WORKSPACE}/semver-action"
        WITH_V: "true"
