on: [push]

jobs:
  semver-action:
    runs-on: ubuntu-latest
    name: semver-action

    steps:
    - uses: actions/checkout@v2
      with:
        repository: stugit/semver-action
        path: "${GITHUB_WORKSPACE}/semver-action"
        fetch-depth: 0
  
    - name: cd directory
      shell: bash
      run: |
        cd "${GITHUB_WORKSPACE}/semver-action"

    - uses: stugit/semver-action@master
      with:
        DEFAULT_BUMP: "minor"
        WITH_V: "true"
