on: [push]

jobs:
  semver-action:
    runs-on: ubuntu-latest
    name: semver-action
    steps:
      - name: semver-action step
        id: semver-action id
        uses: stugit/semver-action@master
